name: routineapp
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.3
  easy_localization: ^3.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.6
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - .env